# Aliases
alias buu="brew update && brew upgrade"
alias tma="tmux attach"
alias gg="lazygit"
alias dd="lazydocker"
alias qq="lazysql"
alias ff="fastfetch"
alias v="nvim"
# alias cat="bat"
alias man="batman"
alias yz="yazi"
alias mtop="sudo mactop"

# alias cd="z"
alias l="eza -l --icons --git -a"
alias lt="eza --tree --level=2 --long --icons --git"
alias ltree="eza --tree --level=2  --icons --git"
alias ls="eza"
alias la="eza -la"
alias lsx="eza -lhHTF -L 1 --git --no-filesize --git-ignore --no-permissions --no-user --ignore-glob=\".git|.vscode\""
alias lsxa="eza -lahHTF -L 1 --git --no-filesize"

alias gaa="git add --all"
alias gco="git checkout"
alias gcmsg="git commit -m"
# alias ggpnp="git pull origin $(current_branch) && git push origin $(current_branch)"
# alias ggpush="git push origin $(current_branch)"
